name = "emailworker"
main = "dist-worker/worker.js"
compatibility_flags = [ "nodejs_compat" ]
compatibility_date = "2024-09-23"

# Additional settings to handle larger worker bundles
usage_model = "bundled"
minify = true

# Specify triggers
[triggers]
crons = []

# Environment - Production
[env.production]
name = "emailworker"
[env.production.vars]
NODE_ENV = "production"
RATE_LIMIT_WINDOW_MS = "900000"    # 15 minutes in milliseconds
RATE_LIMIT_MAX = "50"              # 50 requests per window
EMAIL_RATE_LIMIT_WINDOW_MS = "86400000"  # 24 hours in milliseconds
EMAIL_RATE_LIMIT_MAX = "2"          # 2 emails per window


# Binding configuration for environment variables
# To add secrets, run:
# wrangler secret put EMAIL_USER
# wrangler secret put EMAIL_PASS
# wrangler secret put CORS_ORIGIN
# wrangler secret put EMAIL_SERVICE
# wrangler secret put OAUTH2_CLIENT_ID
# wrangler secret put OAUTH2_CLIENT_SECRET
# wrangler secret put OAUTH2_REFRESH_TOKEN 